update 2.0

diff --git a/templates/default/dockerImage.sh.erb b/templates/default/dockerImage.sh.erb
--- a/templates/default/dockerImage.sh.erb
+++ b/templates/default/dockerImage.sh.erb
@@ -9,6 +9,7 @@ help() {
     exit 1
 }
 
+REGISTRY_URL='<%= @registry_addr %>'
 VALID_IMAGE_NAME='<%= node['conda']['docker']['image-validation-regex'] %>'
 if [ "$1" == "create" ] ; then
 
@@ -29,7 +30,16 @@ if [ "$1" == "create" ] ; then
 <% if node['install']['managed_docker_registry'] == "false" -%>
 elif [ "$1" == "delete" ] ; then
     # Remove tags from docker registry
-    docker exec registry rm -rf /var/lib/registry/docker/registry/v2/repositories/$2/_manifests/tags/$3
+	  # Based on https://gist.github.com/jaytaylor/86d5efaddda926a25fa68c263830dac1
+		curl -g -k -v -sSL -X DELETE "https://$REGISTRY_URL/v2/$2/manifests/$(
+			curl -g -k -sSL -I \
+			-H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+			"https://$REGISTRY_URL/v2/$2/manifests/$(
+				curl -g -k -sSL "https://$REGISTRY_URL/v2/$2/tags/list" | jq -r '.tags[0]'
+			)" \
+			| awk 'tolower($1) == "docker-content-digest:" { print $2 }' \
+			| tr -d $'\r' \
+		)"
 
 elif [ "$1" == "gc" ] ; then
     # Run garbage collection for registry
@@ -44,7 +54,17 @@ elif [ "$1" == "list" ] ; then
 	help
     fi
 
+    docker pull $2 > /dev/null 2>&1
     docker run --rm $2 conda list -n theenv
+
+elif [ "$1" == "check" ] ; then
+    if ! [[ $2 =~ $VALID_IMAGE_NAME ]] ; then
+	echo "error: Not an image name $2" >&2
+	help
+    fi
+
+    docker pull $2 > /dev/null 2>&1
+    docker run --rm $2 pip check
 
 elif [ "$1" == "export" ] ; then
     if ! [[ $2 =~ $VALID_IMAGE_NAME ]] ; then
